apiVersion: v1
kind: Service
metadata:
  name: meal-aks-service
spec:
  selector:
    app: meal-aks
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
